### ISSUE TITLE
`where_indent` appears to be ignored completely by rustfmt

### ISSUE THREAD

**Issue by regexident** [regexident/rustfmt-configs-guide#3]
Running `$ cargo fmt` on [rust-lang/rust/src/librustc/](https://github.com/rust-lang/rust/tree/master/src/librustc/) with:

```toml
where_indent = "Block"
```

followed by another run with:

```toml
where_indent = "Visual"
```

resulted no code changes at all. This got me suspicious and I checked the code:
Turns out rustfmt appears to never actually read from `config.where_indent`.

cc @nrc

**Comment by nrc** [comment]
Fixed in Rustfmt commit 5d9a35050d2b77613e95dbbfa890dd6bfd832812
